# Generated by Django 5.0.7 on 2024-09-21 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vic_payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(default='', max_length=100)),
                ('payment_id', models.CharField(default='', max_length=100)),
                ('paid', models.BooleanField(default=False)),
            ],
        ),
    ]
