# Generated by Django 5.0.4 on 2024-05-16 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_vic_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='vic_event',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='vic_event',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='vic_event',
            name='state',
            field=models.CharField(default='', max_length=100),
        ),
    ]
