# Generated by Django 5.0.4 on 2024-05-16 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_vic_event_city_vic_event_email_vic_event_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vic_event',
            name='event_location',
        ),
    ]
