# Generated by Django 5.0.4 on 2024-05-19 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_remove_vic_event_event_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='vic_event',
            name='your_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
