# Generated by Django 5.0.4 on 2024-05-22 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_vic_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vic_event',
            name='event_time',
        ),
    ]
