# Generated by Django 4.2.13 on 2024-06-07 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_alter_vic_event_city_alter_vic_event_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vic_event',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vic_event',
            name='event_category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vic_event',
            name='state',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vic_event',
            name='your_name',
            field=models.CharField(max_length=100),
        ),
    ]
