# Generated by Django 5.0.7 on 2024-09-20 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_alter_vic_event_city_alter_vic_event_event_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vic_event',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vic_event',
            name='payment_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
