# Generated by Django 5.0.7 on 2024-09-20 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_vic_event_paid_vic_event_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='vic_event',
            name='amount',
            field=models.CharField(default='', max_length=100),
        ),
    ]
