# Generated by Django 5.0.7 on 2024-09-21 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0011_vic_event_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vic_event',
            name='state',
        ),
    ]
