# Generated by Django 5.0.7 on 2024-12-03 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0013_remove_vic_event_amount_remove_vic_event_paid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VicAdminLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=100, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
    ]
